name: chissue
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  dotenv: ^4.2.0
  github: ^9.24.0
  langchain: ^0.7.5
  langchain_openai: ^0.7.1
  televerse: ^1.26.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
